---

- name: Add required repository
  apt_repository:
    repo: ppa:vcmi/ppa

- name: Install required packages
  apt:
    name: "{{ packages }}"

- name: Create user
  user:
    name: "{{ h3_user }}"
    shell: /bin/bash

- name: Check if H3 is already installed
  stat:
    path: "/home/{{ h3_user }}/.local/share/vcmi/"
  register: h3_path

- name: Create required symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlinks }}"

- name: Copy and install H3
  block:
  - name: Create directory for H3
    file:
      path: "{{ h3_remote_dir }}"
      state: directory
      mode: 0755
  - name: Copy H3 GOG installer
    synchronize:
      src: "{{ h3_local_gog_install_file }}"
      dest: "{{ h3_remote_gog_install_file }}"
  - name: Install H3
    command: /usr/games/vcmibuilder --gog {{ h3_remote_gog_install_file }}
    args:
      chdir: "/home/{{ h3_user }}"
    become_user: "{{ h3_user }}"
  when: not h3_path.stat.exists
